language: php

git:
  depth: 2

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - COMPOSER_FLAGS=""
        - ENABLE_CODE_COVERAGE="no"
        - SYMFONY_VERSION=""

matrix:
    fast_failure: true
    include:
        - php: 7.4
          env: ENABLE_CODE_COVERAGE="yes"
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.3
          env: SYMFONY_VERSION=^5.0
    allow_failures:
        - php: nightly

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

before_script:
  - composer update --prefer-dist --no-interaction --optimize-autoloader --no-progress $COMPOSER_FLAGS

script:
  - if [[ "$ENABLE_CODE_COVERAGE" == "yes" ]]; then XDEBUG_MODE=coverage vendor/bin/phpunit -v --coverage-text --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi;
